services:
  postgres:
    image: postgres:16
    container_name: mini-kanban-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_kanban

    ports:
      - '5433:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend

    container_name: mini-kanban-backend

    restart: unless-stopped

    ports:
      - '5000:5000'

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mini_kanban

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend

    container_name: mini-kanban-frontend

    restart: unless-stopped

    ports:
      - '3000:3000'

    depends_on:
      - backend

volumes:
  postgres_data:
